const assert = require('node:assert/strict');
const corpus = require('../analysis/interaction-validation/corpus.json');
const { evaluateCorpus, renderMarkdown } = require('../scripts/report-interaction-validation');

const report = evaluateCorpus(corpus);

assert.equal(corpus.schemaVersion, 'interaction-validation-corpus.v1');
assert.equal(report.schemaVersion, 'interaction-validation-report.v1');
assert.equal(report.summary.caseCount, 46);
assert.equal(report.summary.positiveCount, 24);
assert.equal(report.summary.negativeCount, 22);
assert.equal(report.summary.truePositives, 24);
assert.equal(report.summary.falseNegatives, 0);
assert.equal(report.summary.falsePositives, 0);
assert.equal(report.summary.recall, 1);
assert.equal(report.summary.twoCardRecall, 1);
assert.equal(report.summary.threeCardRecall, 1);
assert.equal(report.summary.sampledPrecision, 1);
assert.equal(report.summary.falsePositiveHubRate, 0);
assert.equal(report.summary.unexplainedRate, 0);
assert.equal(report.summary.averageProofConfidence, 0.75);

const rowsById = new Map(report.rows.map(row => [row.id, row]));
assert.equal(rowsById.get('known-combo-library-exile-win').pass, true, 'library-exile win should stay proven');
assert.equal(rowsById.get('known-combo-imprint-untap-spell-loop').pass, true);
assert.equal(rowsById.get('known-combo-self-untap-ability-copy').pass, true);
assert.equal(rowsById.get('known-combo-hasty-copy-etb-untap').pass, true);
assert.equal(rowsById.get('known-combo-spell-copy-creature-copy').pass, true);
assert.equal(rowsById.get('known-combo-artifact-top-loop-flexible-caster').pass, true);
assert.equal(rowsById.get('known-combo-draw-damage-feedback').pass, true);
assert.equal(rowsById.get('known-combo-recursive-body-sacrifice-mana').pass, true);
assert.equal(rowsById.get('known-combo-layered-recursive-body-death-mana').pass, true);
assert.equal(rowsById.get('known-combo-colorless-amplified-self-untap').pass, true);
assert.equal(rowsById.get('known-combo-mill-lifeloss-feedback').pass, true);
assert.equal(rowsById.get('known-combo-opponent-draw-punisher-win').pass, true);
assert.equal(rowsById.get('known-combo-mill-multiplier-finite-mill').pass, true);
assert.equal(rowsById.get('known-combo-mutual-etb-blink-reset').pass, true);
assert.equal(rowsById.get('known-combo-token-replacement-sacrifice-mana').pass, true);
assert.equal(rowsById.get('known-combo-fixed-lifegain-lifeloss').pass, true);
assert.equal(rowsById.get('known-combo-lifelink-counter-damage').pass, true);
assert.equal(rowsById.get('known-combo-any-type-amplified-self-untap').pass, true);
assert.equal(rowsById.get('negative-low-output-ability-copy').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-expensive-imprint-untap').actualStatus, 'no-proof');
assert.equal(rowsById.get('negative-expensive-recursive-body').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-colored-recursion-colorless-sac').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-colored-recursive-cast-colorless-sac').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-one-way-draw-damage').actualStatus, 'no-proof');
assert.equal(rowsById.get('negative-opponent-draw-damage-feedback').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-one-shot-blink').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-colorless-amplifier-colored-self-untapper').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-one-way-mill-lifeloss').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-small-opponent-draw-punisher').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-small-mill-multiplier').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-mutual-etb-blink-target-mismatch').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-token-replacement-missing-outlet').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-hasty-copy-nonlegendary-target').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-spell-copy-noncreature-copier').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-recursive-body-missing-another-creature').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-lifelink-counter-noncreature-source').actualStatus, 'not-repeatable');
assert.equal(rowsById.get('negative-any-type-amplifier-break-even-only').actualStatus, 'not-repeatable');
assert.deepEqual(rowsById.get('negative-unreplenished-aristocrats').rejectionReasons, ['body is not replenished by the package']);

const coverageById = new Map(report.sourceCoverage.map(source => [source.id, source]));
assert.equal(coverageById.get('commander-spellbook-seeds').caseCount, 4);
assert.equal(coverageById.get('known-combo-seeds').caseCount, 20);
assert.equal(coverageById.get('negative-near-misses').caseCount, 22);
assert.equal(coverageById.get('precon-sample-100').deckCount, 100);
assert.equal(coverageById.get('precon-sample-100').comboDeckCount, 1);
assert.equal(coverageById.get('precon-sample-100').comboPairCount, 4);
assert.equal(coverageById.get('moxfield-bracket-464').deckCount, 464);
assert.deepEqual(coverageById.get('moxfield-bracket-464').brackets, [1, 2, 3, 4, 5]);
assert.equal(coverageById.get('casual-synergy-audit-96').evaluationCount, 96);

assert.deepEqual(report.manualAudit.topMissedCombos, []);
assert.deepEqual(report.manualAudit.topFalsePositives, []);
assert.deepEqual(report.manualAudit.lowConfidenceProofs, []);
assert.ok(report.manualAudit.suspiciousHubs.some(hub => hub.family === 'draw' && hub.count === 42));
assert.ok(report.manualAudit.suspiciousHubs.some(hub => hub.family === 'ramp→sink' && hub.count === 42));

assert.equal(report.deckSmoke[0].status, 'ok');
assert.equal(report.deckSmoke[0].edgeCount, 154);
assert.equal(report.deckSmoke[0].weakInteractionShare, 0.91);

const markdown = renderMarkdown(report);
assert.match(markdown, /## Source coverage/);
assert.match(markdown, /`moxfield-bracket-464`/);
assert.match(markdown, /Missed combos: none/);
assert.match(markdown, /False positives: none/);

process.stdout.write('Interaction validation tests passed\n');
